// src/func/bookmarks/components/bookmark.svelte
<script lang="ts">
    import { onMount, setContext } from "svelte";

    import Group from "./group.svelte";
    import { confirm, Menu, Plugin, showMessage } from "siyuan";
    import { BookmarkDataModel } from "../model";
    import { inputDialog } from "@/libs/dialog";
    // import { simpleDialog } from "@/components/dialog";
    // import Setting from "./setting/index.svelte";
    // import { getBlockByID } from "@/api";

    export let plugin: Plugin;
    export let model: BookmarkDataModel;

    setContext("plugin", plugin);
    setContext("model", model);

    let groups: IBookmarkGroup[] = [];

    let groupComponent: Group[] = [];

    onMount(() => {
        updateShownGroups();
    });

    //TODO 后面加回来
    // const openSetting = () => {
    //     let container = document.createElement("div") as HTMLDivElement;
    //     container.classList.add("fn__flex-1", "fn__flex");
    //     new Setting({
    //         target: container,
    //         props: {
    //             model,
    //         },
    //     });
    //     simpleDialog({
    //         title: "书签设置",
    //         ele: container,
    //         width: '600px'
    //     })
    // }

    function updateShownGroups() {
        groups = model.listGroups();
    }

    function blockIconAdd() {
        inputDialog({
            title: "添加书签组",
            placeholder: "请输入书签组名称",
            confirm: (title: string) => {
                let group = model.newGroup(title);
                groups = [...groups, group];
            },
        });
    }

    let fnRotate = "";
    function blockIconRefresh() {
        fnRotate = "fn__rotate";
        model.updateItems().then(() => {
            setTimeout(() => {
                fnRotate = "";
            }, 500);
        });
    }

    const groupDelete = (e: CustomEvent<IBookmarkGroup>) => {
        const detail = e.detail;
        confirm(
            `是否删除书签组${detail.name}[${detail.id}]?`,
            "⚠️ 删除后无法恢复！确定删除吗？",
            () => {
                if (model.delGroup(detail.id)) {
                    updateShownGroups();
                }
            },
        );
    };

    const groupMove = (
        e: CustomEvent<{
            to: "up" | "down" | "top" | "bottom";
            group: IBookmarkGroup;
        }>,
    ) => {
        const detail = e.detail;
        let srcIdx = groups.findIndex(
            (g: IBookmarkGroup) => g.id === detail.group.id,
        );
        let targetIdx;
        if (detail.to === "up") targetIdx = srcIdx - 1;
        else if (detail.to === 'down') targetIdx = srcIdx + 1;
        else if (detail.to === 'top') targetIdx = 0;
        else if (detail.to === 'bottom') targetIdx = groups.length - 1;
        else return;
        if (targetIdx < 0 || targetIdx >= groups.length) return;
        let targetGroup: IBookmarkGroup = groups[targetIdx];
        model.groupSwapOrder(detail.group.id, targetGroup.id);
        groups = model.listGroups();
    };

    const bookmarkContextMenu = (e: MouseEvent) => {
        let menu = new Menu();
        menu.addItem({
            label: "缓存当前书签",
            icon: "iconDownload",
            click: () => {
                let time = new Date();
                let timeStr = `${time.getFullYear()}-${time.getMonth() + 1}-${time.getDate()} ${time.getHours()}_${time.getMinutes()}_${time.getSeconds()}`;
                let name = `Cache/bookmarks-${timeStr}.json`;
                model.save(name).then(() => {
                    showMessage(`缓存成功: ${name}`);
                });
            },
        });
        menu.open({
            x: e.clientX,
            y: e.clientY,
        });
    };
</script>

<div
    class="fn__flex-1 fn__flex-column file-tree sy__bookmark custom-bookmark-element"
    on:contextmenu={bookmarkContextMenu}
>
    <div class="block__icons">
        <div class="block__logo">
            <svg class="block__logoicon">
                <use xlink:href="#iconBookmark"></use>
            </svg>
            书签
        </div>
        <span class="fn__flex-1"></span>
        <!-- <span
            data-type="setting"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="设置"
            on:click={openSetting}
        >
            <svg class="">
                <use xlink:href="#iconSettings"></use>
            </svg>
        </span> -->
        <span class="fn__space"></span>
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <span
            data-type="add"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="添加书签组"
            on:click={blockIconAdd}
        >
            <svg class="">
                <use xlink:href="#iconAdd"></use>
            </svg>
        </span>
        <span class="fn__space"></span>
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <span
            data-type="refresh"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="刷新"
            on:click={blockIconRefresh}
        >
            <svg class={fnRotate}>
                <use xlink:href="#iconRefresh"></use>
            </svg>
        </span>
        <span class="fn__space"></span>
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <span
            data-type="expand"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="展开 Ctrl+↓"
            on:click={() => {
                groupComponent.forEach((group) => group.toggleOpen(true));
                model.save();
            }}
        >
            <svg>
                <use xlink:href="#iconExpand"></use>
            </svg>
        </span>
        <span class="fn__space"></span>
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <span
            data-type="collapse"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="折叠 Ctrl+↑"
            on:click={() => {
                groupComponent.forEach((group) => group.toggleOpen(false));
                model.save();
            }}
        >
            <svg>
                <use xlink:href="#iconContract"></use>
            </svg>
        </span>
        <span class="fn__space"></span>
        <span
            data-type="min"
            class="block__icon b3-tooltips b3-tooltips__sw"
            aria-label="最小化 Ctrl+W"
        >
            <svg>
                <use xlink:href="#iconMin"></use>
            </svg>
        </span>
    </div>
    <div class="fn__flex-1" style="margin-bottom: 8px">
        <ul class="b3-list b3-list--background" id="custom-bookmark-body">
            {#each groups as group, i (group.id)}
                <Group
                    {group}
                    bind:this={groupComponent[i]}
                    on:deleteGroup={groupDelete}
                    on:move={groupMove}
                />
            {/each}
        </ul>
    </div>
</div>

// src/func/bookmarks/components/bookmark.tsx
import { Component, createEffect, createSignal } from "solid-js";
// import { render } from "solid-js/web";
import Group from "./group";
import { confirm, Menu, Plugin, showMessage } from "siyuan";
import { BookmarkDataModel } from "../model";
import { inputDialog } from "@/libs/dialog";

import { BookmarkContext } from "./context";

import "./index.scss";

interface Props {
    plugin: Plugin;
    model: BookmarkDataModel;
}

const BookmarkComponent: Component<Props> = (props) => {
    const [groups, setGroups] = createSignal<IBookmarkGroup[]>([]);
    const [groupComponent, setGroupComponent] = createSignal<Group[]>([]);
    const [fnRotate, setFnRotate] = createSignal("");

    const updateShownGroups = () => {
        setGroups(props.model.listGroups());
    };

    const blockIconAdd = () => {
        inputDialog({
            title: "添加书签组",
            placeholder: "请输入书签组名称",
            confirm: (title: string) => {
                const group = props.model.newGroup(title);
                setGroups([...groups(), group]);
            },
        });
    };

    const blockIconRefresh = () => {
        setFnRotate("fn__rotate");
        props.model.updateItems().then(() => {
            setTimeout(() => {
                setFnRotate("");
            }, 500);
        });
    };

    const groupDelete = (detail: IBookmarkGroup) => {
        confirm(
            `是否删除书签组${detail.name}[${detail.id}]?`,
            "⚠️ 删除后无法恢复！确定删除吗？",
            () => {
                if (props.model.delGroup(detail.id)) {
                    updateShownGroups();
                }
            }
        );
    };

    const groupMove = (
        detail: {
            to: "up" | "down" | "top" | "bottom";
            group: IBookmarkGroup;
        }
    ) => {
        const srcIdx = groups().findIndex(
            (g: IBookmarkGroup) => g.id === detail.group.id
        );
        let targetIdx;
        if (detail.to === "up") targetIdx = srcIdx - 1;
        else if (detail.to === "down") targetIdx = srcIdx + 1;
        else if (detail.to === "top") targetIdx = 0;
        else if (detail.to === "bottom") targetIdx = groups().length - 1;
        else return;
        if (targetIdx < 0 || targetIdx >= groups().length) return;
        const targetGroup: IBookmarkGroup = groups()[targetIdx];
        props.model.groupSwapOrder(detail.group.id, targetGroup.id);
        setGroups(props.model.listGroups());
    };

    const bookmarkContextMenu = (e: MouseEvent) => {
        const menu = new Menu();
        menu.addItem({
            label: "缓存当前书签",
            icon: "iconDownload",
            click: () => {
                const time = new Date();
                const timeStr = `${time.getFullYear()}-${time.getMonth() + 1}-${time.getDate()} ${time.getHours()}_${time.getMinutes()}_${time.getSeconds()}`;
                const name = `Cache/bookmarks-${timeStr}.json`;
                props.model.save(name).then(() => {
                    showMessage(`缓存成功: ${name}`);
                });
            },
        });
        menu.open({
            x: e.clientX,
            y: e.clientY,
        });
    };

    createEffect(() => {
        updateShownGroups();
    });

    const Bookmark = () => (
        <div
            class="fn__flex-1 fn__flex-column file-tree sy__bookmark custom-bookmark-element"
            onContextMenu={bookmarkContextMenu}
        >
            <div class="block__icons">
                <div class="block__logo">
                    <svg class="block__logoicon">
                        <use href="#iconBookmark"></use>
                    </svg>
                    书签
                </div>
                <span class="fn__flex-1"></span>
                <span class="fn__space"></span>
                <span
                    data-type="add"
                    class="block__icon b3-tooltips b3-tooltips__sw"
                    aria-label="添加书签组"
                    onClick={blockIconAdd}
                >
                    <svg class="">
                        <use href="#iconAdd"></use>
                    </svg>
                </span>
                <span class="fn__space"></span>
                <span
                    data-type="refresh"
                    class="block__icon b3-tooltips b3-tooltips__sw"
                    aria-label="刷新"
                    onClick={blockIconRefresh}
                >
                    <svg class={fnRotate()}>
                        <use href="#iconRefresh"></use>
                    </svg>
                </span>
                <span class="fn__space"></span>
                <span
                    data-type="expand"
                    class="block__icon b3-tooltips b3-tooltips__sw"
                    aria-label="展开 Ctrl+↓"
                    onClick={() => {
                        groupComponent().forEach((group) => group.toggleOpen(true));
                        props.model.save();
                    }}
                >
                    <svg>
                        <use href="#iconExpand"></use>
                    </svg>
                </span>
                <span class="fn__space"></span>
                <span
                    data-type="collapse"
                    class="block__icon b3-tooltips b3-tooltips__sw"
                    aria-label="折叠 Ctrl+↑"
                    onClick={() => {
                        groupComponent().forEach((group) => group.toggleOpen(false));
                        props.model.save();
                    }}
                >
                    <svg>
                        <use href="#iconContract"></use>
                    </svg>
                </span>
                <span class="fn__space"></span>
                <span
                    data-type="min"
                    class="block__icon b3-tooltips b3-tooltips__sw"
                    aria-label="最小化 Ctrl+W"
                >
                    <svg>
                        <use href="#iconMin"></use>
                    </svg>
                </span>
            </div>
            <div class="fn__flex-1" style="margin-bottom: 8px">
                <ul class="b3-list b3-list--background" id="custom-bookmark-body">
                    {groups().map((group, i) => (
                        <Group
                            group={group}
                            ref={(el) => (groupComponent()[i] = el)}
                            groupDelete={groupDelete}
                            groupMove={groupMove}
                        />
                    ))}
                </ul>
            </div>
        </div>
    );

    return (<BookmarkContext.Provider value={[props.plugin, props.model]}>
        <Bookmark />
    </BookmarkContext.Provider>);
};

export default BookmarkComponent;
