// src/libs/components/setting-panel.tsx
// Copyright (c) 2023 by frostime All Rights Reserved.
// Author       : frostime
// Date         : 2023-07-01 19:23:50
// FilePath     : /src/libs/setting-panel.tsx
// LastEditTime : 2024-06-08 18:25:34
// Description  :

import { Component, createSignal, For, Show, JSXElement } from "solid-js";
import ItemWrap from "./item-wrap";
import InputItem from "./item-input";

interface SettingPanelProps {
    group: string;
    settingItems: ISettingItem[];
    display?: boolean;
    onChanged: (e: { group: string, key: string, value: any }) => void;
    children?: JSXElement
}

const SettingPanel: Component<SettingPanelProps> = (props) => {
    const { group, settingItems, display = true, onChanged } = props;
    const [fn__none, _] = createSignal(display ? "" : "fn__none");

    return (
        <Show when={display}>
            <div class={`config__tab-container ${fn__none()}`} data-name={group}>
                {props.children}
                <For each={settingItems}>
                    {(item) => (
                        <ItemWrap
                            title={item.title}
                            description={item.description}
                            direction={item?.direction}
                        >
                            <InputItem
                                type={item.type}
                                key={item.key}
                                value={item.value}
                                placeholder={item?.placeholder}
                                options={item?.options}
                                slider={item?.slider}
                                button={item?.button}
                                changed={(v) => onChanged({ group: group, key: item.key, value: v })}
                            />
                        </ItemWrap>
                    )}
                </For>
            </div>
        </Show>
    );
};

export default SettingPanel;

// src/libs/setting-panel.svelte
<!--
 Copyright (c) 2023 by frostime All Rights Reserved.
 Author       : frostime
 Date         : 2023-07-01 19:23:50
 FilePath     : /src/libs/components/setting-panel.svelte
 LastEditTime : 2024-06-07 20:06:43
 Description  : 
-->
<script lang="ts">
    import { createEventDispatcher } from "svelte";
    import SettingItemWrap from "./setting-item-wrap.svelte";
    import InputItem from "./input-item.svelte";

    export let group: string;
    export let settingItems: ISettingItem[];
    export let display: boolean = true;

    const dispatch = createEventDispatcher();

    function onClick( {detail}) {
        dispatch("click", { key: detail.key });
    }
    function onChanged( {detail}) {
        dispatch("changed", {group: group, ...detail});
    }

    $: fn__none = display ? "" : "fn__none";

</script>

<div class="config__tab-container {fn__none}" data-name={group}>
    {#each settingItems as item (item.key)}
        <SettingItemWrap
            title={item.title}
            description={item.description}
            direction={item.direction}
        > 
            <InputItem
                type={item.type}
                key={item.key}
                bind:value={item.value}
                placeholder={item?.placeholder}
                options={item?.options}
                slider={item?.slider}
                button={item?.button}
                on:click={onClick}
                on:changed={onChanged}
            />
        </SettingItemWrap>
    {/each}
</div>
